//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polakken.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polakken.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] NationalInstruments_Common {
            get {
                object obj = ResourceManager.GetObject("NationalInstruments_Common", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NationalInstruments_Common_Native {
            get {
                object obj = ResourceManager.GetObject("NationalInstruments_Common_Native", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NationalInstruments_Common1 {
            get {
                object obj = ResourceManager.GetObject("NationalInstruments_Common1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;doc xmlns:ni=&quot;urn:ni&quot;&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;NationalInstruments.Common&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:NationalInstruments.WaveformTiming&quot;&gt;
        ///      &lt;summary&gt;
        ///        Provides a class that encapsulates waveform timing information.
        ///      &lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;F:NationalInstruments.WaveformTiming.Empty&quot;&gt;
        ///      &lt;summary&gt;
        ///        Represents a WaveformTiming that has no time stamp, time offset, or sample interval.
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NationalInstruments_Common2 {
            get {
                return ResourceManager.GetString("NationalInstruments_Common2", resourceCulture);
            }
        }
        
        internal static byte[] NationalInstruments_DAQmx {
            get {
                object obj = ResourceManager.GetObject("NationalInstruments_DAQmx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NationalInstruments_DAQmx1 {
            get {
                object obj = ResourceManager.GetObject("NationalInstruments_DAQmx1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;doc xmlns:ni=&quot;urn:ni&quot;&gt;
        ///  &lt;assembly ninamespaces=&quot;NationalInstruments.DAQmx&quot;&gt;
        ///    &lt;name&gt;NationalInstruments.DAQmx&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:NationalInstruments.DAQmx.Channel&quot; nitypekind=&quot;Class&quot; nieditor=&quot;Sebastius&quot; niapproved=&quot;True&quot;
        ///            nilastupdated=&quot;5/22/2012 8:56:09 AM&quot; niupdatedby=&quot;Sebastius&quot; nidisplayname=&quot;Channel&quot; nihasget=&quot;0&quot;
        ///            nihasset=&quot;0&quot; niparameters=&quot;&quot; niparametertypes=&quot;&quot; nireturnvaluetype=&quot;&quot;&gt;
        ///      &lt;su [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NationalInstruments_DAQmx2 {
            get {
                return ResourceManager.GetString("NationalInstruments_DAQmx2", resourceCulture);
            }
        }
        
        internal static byte[] NationalInstruments_MStudioCLM {
            get {
                object obj = ResourceManager.GetObject("NationalInstruments_MStudioCLM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NationalInstruments_NiLmClientDLL {
            get {
                object obj = ResourceManager.GetObject("NationalInstruments_NiLmClientDLL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnArrowDown {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnArrowDownDown {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnArrowDownDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnArrowUp {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnArrowUpDown {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnArrowUpDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnClose {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnFiltrer {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnFiltrer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnFiltrerDown {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnFiltrerDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnLagre {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnLagre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnLagreDown {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnLagreDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnLeggTil {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnLeggTil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnLeggTilDown {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnLeggTilDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnLoggInn {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnLoggInn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnLoggInnNed {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnLoggInnNed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnMinimize {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnMinimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnMinus {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnMinus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnMinusDisabled {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnMinusDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnNullstillFilter {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnNullstillFilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnNullstillFilterDown {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnNullstillFilterDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnPlus {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnPlusDisabeld {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnPlusDisabeld", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnSlett {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnSlett", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_btnSlettDown {
            get {
                object obj = ResourceManager.GetObject("Polakken_btnSlettDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_imgGuiForm {
            get {
                object obj = ResourceManager.GetObject("Polakken_imgGuiForm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_imgLoggInn {
            get {
                object obj = ResourceManager.GetObject("Polakken_imgLoggInn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_imgPowerOff {
            get {
                object obj = ResourceManager.GetObject("Polakken_imgPowerOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_imgPowerOn {
            get {
                object obj = ResourceManager.GetObject("Polakken_imgPowerOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_imgSensorIn {
            get {
                object obj = ResourceManager.GetObject("Polakken_imgSensorIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_imgSensorOut {
            get {
                object obj = ResourceManager.GetObject("Polakken_imgSensorOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_imgTab {
            get {
                object obj = ResourceManager.GetObject("Polakken_imgTab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polakken_LogForn {
            get {
                object obj = ResourceManager.GetObject("Polakken_LogForn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
