//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polakken.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polakken.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnArrowDown {
            get {
                object obj = ResourceManager.GetObject("btnArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnArrowDownDown {
            get {
                object obj = ResourceManager.GetObject("btnArrowDownDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnArrowUp {
            get {
                object obj = ResourceManager.GetObject("btnArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnArrowUpDown {
            get {
                object obj = ResourceManager.GetObject("btnArrowUpDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnClose {
            get {
                object obj = ResourceManager.GetObject("btnClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnFiltrer {
            get {
                object obj = ResourceManager.GetObject("btnFiltrer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnFiltrerDown {
            get {
                object obj = ResourceManager.GetObject("btnFiltrerDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnLagre {
            get {
                object obj = ResourceManager.GetObject("btnLagre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnLagreDown {
            get {
                object obj = ResourceManager.GetObject("btnLagreDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnLeggTil {
            get {
                object obj = ResourceManager.GetObject("btnLeggTil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnLeggTilDown {
            get {
                object obj = ResourceManager.GetObject("btnLeggTilDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnLogg {
            get {
                object obj = ResourceManager.GetObject("btnLogg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnMinimize {
            get {
                object obj = ResourceManager.GetObject("btnMinimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnMinus {
            get {
                object obj = ResourceManager.GetObject("btnMinus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnMinusDisabled {
            get {
                object obj = ResourceManager.GetObject("btnMinusDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnNullstillFilter {
            get {
                object obj = ResourceManager.GetObject("btnNullstillFilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnNullstillFilterDown {
            get {
                object obj = ResourceManager.GetObject("btnNullstillFilterDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnPlus {
            get {
                object obj = ResourceManager.GetObject("btnPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnPlusDisabeld {
            get {
                object obj = ResourceManager.GetObject("btnPlusDisabeld", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnSlett {
            get {
                object obj = ResourceManager.GetObject("btnSlett", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnSlettDown {
            get {
                object obj = ResourceManager.GetObject("btnSlettDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgGuiForm {
            get {
                object obj = ResourceManager.GetObject("imgGuiForm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgPowerOff {
            get {
                object obj = ResourceManager.GetObject("imgPowerOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgPowerOn {
            get {
                object obj = ResourceManager.GetObject("imgPowerOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgSensorIn {
            get {
                object obj = ResourceManager.GetObject("imgSensorIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgSensorOut {
            get {
                object obj = ResourceManager.GetObject("imgSensorOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgTab {
            get {
                object obj = ResourceManager.GetObject("imgTab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogForn {
            get {
                object obj = ResourceManager.GetObject("LogForn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NationalInstruments_Common {
            get {
                object obj = ResourceManager.GetObject("NationalInstruments_Common", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NationalInstruments_Common_Native {
            get {
                object obj = ResourceManager.GetObject("NationalInstruments_Common_Native", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NationalInstruments_Common1 {
            get {
                object obj = ResourceManager.GetObject("NationalInstruments_Common1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;doc xmlns:ni=&quot;urn:ni&quot;&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;NationalInstruments.Common&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:NationalInstruments.WaveformTiming&quot;&gt;
        ///      &lt;summary&gt;
        ///            Provides a class that encapsulates waveform timing information.
        ///            &lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;F:NationalInstruments.WaveformTiming.Empty&quot;&gt;
        ///      &lt;summary&gt;
        ///            Represents a WaveformTiming that has no time stamp, time offset, or sample i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NationalInstruments_Common2 {
            get {
                return ResourceManager.GetString("NationalInstruments_Common2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NationalInstruments_DAQmx {
            get {
                object obj = ResourceManager.GetObject("NationalInstruments_DAQmx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NationalInstruments_DAQmx1 {
            get {
                object obj = ResourceManager.GetObject("NationalInstruments_DAQmx1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;doc xmlns:ni=&quot;urn:ni&quot;&gt;
        ///  &lt;assembly ninamespaces=&quot;NationalInstruments.DAQmx&quot;&gt;
        ///    &lt;name&gt;NationalInstruments.DAQmx&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:NationalInstruments.DAQmx.Channel&quot; nitypekind=&quot;Class&quot; nieditor=&quot;Sebastius&quot; niapproved=&quot;True&quot; nilastupdated=&quot;5/22/2012 8:56:09 AM&quot; niupdatedby=&quot;Sebastius&quot; nidisplayname=&quot;Channel&quot; nihasget=&quot;0&quot; nihasset=&quot;0&quot; niparameters=&quot;&quot; niparametertypes=&quot;&quot; nireturnvaluetype=&quot;&quot;&gt;
        ///      &lt;summary&gt;Represents a channel o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NationalInstruments_DAQmx2 {
            get {
                return ResourceManager.GetString("NationalInstruments_DAQmx2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NationalInstruments_MStudioCLM {
            get {
                object obj = ResourceManager.GetObject("NationalInstruments_MStudioCLM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NationalInstruments_NiLmClientDLL {
            get {
                object obj = ResourceManager.GetObject("NationalInstruments_NiLmClientDLL", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
